//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gwarancja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gwarancja()
        {
            this.Zamowienie_szczegol = new HashSet<Zamowienie_szczegol>();
            this.Zamowienie_szczegol_pojazd = new HashSet<Zamowienie_szczegol_pojazd>();
        }
    
        public int ID_gwarancja { get; set; }
        public string Opis_gwarancja { get; set; }
        public int Okres_gwarancja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol_pojazd> Zamowienie_szczegol_pojazd { get; set; }
    }
}
