//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola_parametr_polprodukt
    {
        public int ID_kontrola_parametr_polprodukt { get; set; }
        public int ID_kontrola_jakosci_polprodukt { get; set; }
        public int ID_parametr_polprodukt { get; set; }
        public decimal Wartosc { get; set; }
    
        public virtual Kontrola_jakosci_polprodukt Kontrola_jakosci_polprodukt { get; set; }
        public virtual Parametr_polprodukt Parametr_polprodukt { get; set; }
    }
}
