//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marka_model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marka_model()
        {
            this.Typ_pojazd_model = new HashSet<Typ_pojazd_model>();
        }
    
        public int ID_marka_model { get; set; }
        public int ID_marka_pojazd { get; set; }
        public int ID_model_pojazd { get; set; }
    
        public virtual Marka_pojazd_slownik Marka_pojazd_slownik { get; set; }
        public virtual Model_pojazd_slownik Model_pojazd_slownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Typ_pojazd_model> Typ_pojazd_model { get; set; }
    }
}
