//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miejsce_magazynowanie_produkt
    {
        public int ID_miejsce_magazynowanie_produkt { get; set; }
        public int ID_poziom_magazynowanie { get; set; }
        public int ID_produkt { get; set; }
        public int Nr_miejsca { get; set; }
    
        public virtual Poziom_magazynowanie Poziom_magazynowanie { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
