//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Montaz_pojazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Montaz_pojazd()
        {
            this.Kontrola_jakosci_pojazd = new HashSet<Kontrola_jakosci_pojazd>();
            this.Proces_montaz_pojazd = new HashSet<Proces_montaz_pojazd>();
        }
    
        public int ID_montaz_pojazd { get; set; }
        public int ID_pracownik { get; set; }
        public int ID_zamowienie_szczegol_pojazd { get; set; }
        public System.DateTime Czas_od { get; set; }
        public Nullable<System.DateTime> Czas_do { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_jakosci_pojazd> Kontrola_jakosci_pojazd { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Zamowienie_szczegol_pojazd Zamowienie_szczegol_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_montaz_pojazd> Proces_montaz_pojazd { get; set; }
    }
}
