//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazd()
        {
            this.Marka_model_pojazd = new HashSet<Marka_model_pojazd>();
            this.Miejsce_magazynowanie_pojazd = new HashSet<Miejsce_magazynowanie_pojazd>();
            this.Proces_montaz_pojazd_czynnosc = new HashSet<Proces_montaz_pojazd_czynnosc>();
            this.Szczegol_reklamacja_pojazd = new HashSet<Szczegol_reklamacja_pojazd>();
            this.Wersja_wyposazenia_pojazd = new HashSet<Wersja_wyposazenia_pojazd>();
            this.Zamowienie_szczegol_pojazd = new HashSet<Zamowienie_szczegol_pojazd>();
            this.Zwrot_pojazd = new HashSet<Zwrot_pojazd>();
        }
    
        public int ID_pojazd { get; set; }
        public string Nr_VIN { get; set; }
        public int Rok_produkcji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marka_model_pojazd> Marka_model_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowanie_pojazd> Miejsce_magazynowanie_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_montaz_pojazd_czynnosc> Proces_montaz_pojazd_czynnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_reklamacja_pojazd> Szczegol_reklamacja_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wersja_wyposazenia_pojazd> Wersja_wyposazenia_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol_pojazd> Zamowienie_szczegol_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwrot_pojazd> Zwrot_pojazd { get; set; }
    }
}
