//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poziom_magazynowanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poziom_magazynowanie()
        {
            this.Miejsce_magazynowanie_pojazd = new HashSet<Miejsce_magazynowanie_pojazd>();
            this.Miejsce_magazynowanie_polprodukt = new HashSet<Miejsce_magazynowanie_polprodukt>();
            this.Miejsce_magazynowanie_produkt = new HashSet<Miejsce_magazynowanie_produkt>();
            this.Parametr_poziom_magazynowanie = new HashSet<Parametr_poziom_magazynowanie>();
        }
    
        public int ID_poziom_magazynowanie { get; set; }
        public int ID_magazynowanie { get; set; }
        public int Poziom { get; set; }
    
        public virtual Magazynowanie_slownik Magazynowanie_slownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowanie_pojazd> Miejsce_magazynowanie_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowanie_polprodukt> Miejsce_magazynowanie_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowanie_produkt> Miejsce_magazynowanie_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_poziom_magazynowanie> Parametr_poziom_magazynowanie { get; set; }
    }
}
