//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Dane_adresowe_pracownik = new HashSet<Dane_adresowe_pracownik>();
            this.Email_pracownik = new HashSet<Email_pracownik>();
            this.Kontrola_jakosci_pojazd = new HashSet<Kontrola_jakosci_pojazd>();
            this.Kontrola_jakosci_polprodukt = new HashSet<Kontrola_jakosci_polprodukt>();
            this.Kontrola_jakosci_produkt = new HashSet<Kontrola_jakosci_produkt>();
            this.Montaz_pojazd = new HashSet<Montaz_pojazd>();
            this.Nieobecnosc = new HashSet<Nieobecnosc>();
            this.Nr_telefon_pracownik = new HashSet<Nr_telefon_pracownik>();
            this.Obsluga_pracownik = new HashSet<Obsluga_pracownik>();
            this.Reklamacja_pojazd = new HashSet<Reklamacja_pojazd>();
            this.Reklamacja_produkt = new HashSet<Reklamacja_produkt>();
            this.Stan_realizacji_zamowienie_czesc = new HashSet<Stan_realizacji_zamowienie_czesc>();
            this.Stan_realizacji_zamowienie_maszyna = new HashSet<Stan_realizacji_zamowienie_maszyna>();
            this.Stan_realizacji_zamowienie_narzedzie = new HashSet<Stan_realizacji_zamowienie_narzedzie>();
            this.Stan_realizacji_zamowienie_produkt = new HashSet<Stan_realizacji_zamowienie_produkt>();
            this.Stan_realizacji_zamowienie_material = new HashSet<Stan_realizacji_zamowienie_material>();
            this.Stan_realizacji_zamowienie_polprodukt = new HashSet<Stan_realizacji_zamowienie_polprodukt>();
            this.Stanowisko_pracownik = new HashSet<Stanowisko_pracownik>();
            this.Szkolenie_pracownik = new HashSet<Szkolenie_pracownik>();
            this.Wytwarzanie = new HashSet<Wytwarzanie>();
            this.Zamowienie_maszyna = new HashSet<Zamowienie_maszyna>();
            this.Zamowienie_narzedzie = new HashSet<Zamowienie_narzedzie>();
            this.Zamowienie = new HashSet<Zamowienie>();
            this.Zamowienie_produkt = new HashSet<Zamowienie_produkt>();
            this.Zamowienie_material = new HashSet<Zamowienie_material>();
            this.Zamowienie_polprodukt = new HashSet<Zamowienie_polprodukt>();
            this.Zamowienie_czesc = new HashSet<Zamowienie_czesc>();
        }
    
        public int ID_pracownik { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Nr_dowodu { get; set; }
        public long Pesel { get; set; }
        public int ID_wyksztalcenie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dane_adresowe_pracownik> Dane_adresowe_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email_pracownik> Email_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_jakosci_pojazd> Kontrola_jakosci_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_jakosci_polprodukt> Kontrola_jakosci_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrola_jakosci_produkt> Kontrola_jakosci_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Montaz_pojazd> Montaz_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nieobecnosc> Nieobecnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nr_telefon_pracownik> Nr_telefon_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obsluga_pracownik> Obsluga_pracownik { get; set; }
        public virtual Wyksztalcenie Wyksztalcenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja_pojazd> Reklamacja_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja_produkt> Reklamacja_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_czesc> Stan_realizacji_zamowienie_czesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_maszyna> Stan_realizacji_zamowienie_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_narzedzie> Stan_realizacji_zamowienie_narzedzie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_produkt> Stan_realizacji_zamowienie_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_material> Stan_realizacji_zamowienie_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_zamowienie_polprodukt> Stan_realizacji_zamowienie_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stanowisko_pracownik> Stanowisko_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szkolenie_pracownik> Szkolenie_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wytwarzanie> Wytwarzanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_maszyna> Zamowienie_maszyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_narzedzie> Zamowienie_narzedzie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_produkt> Zamowienie_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_material> Zamowienie_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_polprodukt> Zamowienie_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_czesc> Zamowienie_czesc { get; set; }
    }
}
