//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_montaz_pojazd_czynnosc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proces_montaz_pojazd_czynnosc()
        {
            this.Proces_montaz_pojazd = new HashSet<Proces_montaz_pojazd>();
        }
    
        public int ID_proces_montaz_pojazd_czynnosc { get; set; }
        public int ID_pojazd { get; set; }
        public int ID_czynnosc_produkcyjna { get; set; }
        public int ID_stanowisko_produkcyjne { get; set; }
        public int Czas_trwania { get; set; }
    
        public virtual Czynnosc_produkcyjna Czynnosc_produkcyjna { get; set; }
        public virtual Pojazd Pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_montaz_pojazd> Proces_montaz_pojazd { get; set; }
        public virtual Stanowisko_produkcyjne Stanowisko_produkcyjne { get; set; }
    }
}
