//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_montaz_pojazd
    {
        public int ID_proces_montaz_pojazd { get; set; }
        public int ID_montaz_pojazd { get; set; }
        public int ID_proces_montaz_pojazd_czynnosc { get; set; }
    
        public virtual Montaz_pojazd Montaz_pojazd { get; set; }
        public virtual Proces_montaz_pojazd_czynnosc Proces_montaz_pojazd_czynnosc { get; set; }
    }
}
