//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamacja_pojazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reklamacja_pojazd()
        {
            this.Szczegol_reklamacja_pojazd = new HashSet<Szczegol_reklamacja_pojazd>();
            this.Zwrot_pojazd = new HashSet<Zwrot_pojazd>();
        }
    
        public int ID_reklamacja_pojazd { get; set; }
        public int ID_pracownik { get; set; }
        public int ID_zamowienie { get; set; }
        public System.DateTime Data_reklamacja { get; set; }
        public string Opis_reklamacja { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_reklamacja_pojazd> Szczegol_reklamacja_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwrot_pojazd> Zwrot_pojazd { get; set; }
    }
}
