//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slownik_polprodukt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slownik_polprodukt()
        {
            this.Miejsce_magazynowanie_polprodukt = new HashSet<Miejsce_magazynowanie_polprodukt>();
            this.Parametr_polprodukt = new HashSet<Parametr_polprodukt>();
            this.Proces_polprodukt_czynnosc = new HashSet<Proces_polprodukt_czynnosc>();
            this.Sklad_polprodukt = new HashSet<Sklad_polprodukt>();
            this.Sklad_produkt = new HashSet<Sklad_produkt>();
            this.Szczegoly_zamowienie_polprodukt = new HashSet<Szczegoly_zamowienie_polprodukt>();
        }
    
        public int ID_polprodukt { get; set; }
        public string Nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowanie_polprodukt> Miejsce_magazynowanie_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_polprodukt> Parametr_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_polprodukt_czynnosc> Proces_polprodukt_czynnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_polprodukt> Sklad_polprodukt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_produkt> Sklad_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegoly_zamowienie_polprodukt> Szczegoly_zamowienie_polprodukt { get; set; }
    }
}
