//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_zamowienie_produkt
    {
        public int ID_szczegoly_zamowienie_produkt { get; set; }
        public int ID_zamowienie_produkt { get; set; }
        public int ID_produkt { get; set; }
        public int Ilosc { get; set; }
        public int Cena { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Zamowienie_produkt Zamowienie_produkt { get; set; }
    }
}
