//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szczegoly_zamowienie_polprodukt
    {
        public int ID_szczegoly_zamowienie_polprodukt { get; set; }
        public int ID_zamowienie_polprodukt { get; set; }
        public int ID_polprodukt { get; set; }
        public int Ilosc { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Slownik_polprodukt Slownik_polprodukt { get; set; }
        public virtual Zamowienie_polprodukt Zamowienie_polprodukt { get; set; }
    }
}
