//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typ_reklamacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Typ_reklamacja()
        {
            this.Szczegol_reklamacja_pojazd = new HashSet<Szczegol_reklamacja_pojazd>();
            this.Szczegol_reklamacja_produkt = new HashSet<Szczegol_reklamacja_produkt>();
        }
    
        public int ID_typ_reklamacja { get; set; }
        public string Nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_reklamacja_pojazd> Szczegol_reklamacja_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_reklamacja_produkt> Szczegol_reklamacja_produkt { get; set; }
    }
}
