//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typ_pojazd_model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Typ_pojazd_model()
        {
            this.Marka_model_pojazd = new HashSet<Marka_model_pojazd>();
            this.Typ_pojazd_model_silnik = new HashSet<Typ_pojazd_model_silnik>();
        }
    
        public int ID_typ_pojazd_model { get; set; }
        public int ID_marka_model { get; set; }
        public int ID_typ_pojazd { get; set; }
    
        public virtual Marka_model Marka_model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marka_model_pojazd> Marka_model_pojazd { get; set; }
        public virtual Typ_pojazd_slownik Typ_pojazd_slownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Typ_pojazd_model_silnik> Typ_pojazd_model_silnik { get; set; }
    }
}
