//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowa
    {
        public int ID_umowa { get; set; }
        public int ID_rodzaj_umowy { get; set; }
        public int ID_stanowisko_pracownik { get; set; }
        public System.DateTime Data_od { get; set; }
        public Nullable<System.DateTime> Data_do { get; set; }
    
        public virtual Rodzaj_umowy Rodzaj_umowy { get; set; }
        public virtual Stanowisko_pracownik Stanowisko_pracownik { get; set; }
    }
}
