//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Czas_po_szeregowaniu
    {
        public int ID_maszyna_nr { get; set; }
        public int Zadanie_produkcyjne { get; set; }
        public int Czas_trwania { get; set; }
    }
}
