//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Kontrola_jakosci_pojazd_kolejka
    {
        public int ID_montaz_pojazd { get; set; }
        public int ID_pojazd { get; set; }
        public string Nr_VIN { get; set; }
    }
}
