//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Kontrola_pozytywna_polprodukt
    {
        public int ID_wytwarzanie { get; set; }
        public int ID_polprodukt { get; set; }
        public string Polprodukt { get; set; }
        public Nullable<int> Wynik_kontrola { get; set; }
        public int ID_zamowienie { get; set; }
    }
}
