//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Magazynowanie_pojazd
    {
        public int ID_miejsce_magazynowanie_pojazd { get; set; }
        public string Nr_VIN { get; set; }
        public int Nr_miejsca { get; set; }
        public string Nazwa { get; set; }
        public int Poziom { get; set; }
    }
}
