//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Proces_montaz_wykonane
    {
        public int ID { get; set; }
        public string Nr_VIN { get; set; }
        public string Czynność_produkcyjna { get; set; }
        public string Stanowisko { get; set; }
        public System.DateTime Czas_od { get; set; }
        public Nullable<System.DateTime> Czas_do { get; set; }
        public string Pracownik { get; set; }
        public int ID_montaz_pojazd { get; set; }
        public int ID_pojazd { get; set; }
        public int ID_zamowienie { get; set; }
    }
}
