//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sklad_stanowisko_produkcyjne_maszyna_polprodukt
    {
        public int ID_Stanowiska { get; set; }
        public string Nr_seryjny_maszyny { get; set; }
        public string Maszyna { get; set; }
        public decimal Koszt_roboczogodziny__PLN_ { get; set; }
        public string Czynność { get; set; }
    }
}
