//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Stanowiska_czynnosci1
    {
        public string Nazwa_stanowiska { get; set; }
        public string Nazwa { get; set; }
        public int Czas_trwania { get; set; }
        public int ID_proces_polprodukt { get; set; }
    }
}
