//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Wybor_silnika_zrobione
    {
        public int ID_typ_pojazd { get; set; }
        public string Nazwa_typ { get; set; }
        public string Nr_VIN { get; set; }
        public int ID_marka_model { get; set; }
        public int ID_pojazd { get; set; }
        public int Rok_produkcji { get; set; }
        public string Marka_model { get; set; }
    }
}
