//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Wybor_model1
    {
        public int ID_marka_model { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Rok_produkcji_od { get; set; }
        public int Rok_produkcji_do { get; set; }
    }
}
