//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienie_produkt
    {
        public int ID_zamowienie_produkt { get; set; }
        public string Nr_dowodu { get; set; }
        public string Nr_VIN { get; set; }
        public string Nazwa_dostawca { get; set; }
        public System.DateTime Data_zamowienia { get; set; }
    }
}
