//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienie_pojazd
    {
        public int ID_zamowienie { get; set; }
        public System.DateTime Data_zamowienie { get; set; }
        public string Numer_telefonu { get; set; }
        public string Nr_dowodu { get; set; }
        public int ID_typ_zamowienie { get; set; }
        public string Nazwisko_klienta { get; set; }
        public string Imię_klienta { get; set; }
        public string Rodzaj_zamowienie { get; set; }
        public string Nazwisko_pracownika { get; set; }
        public string Imię_pracownika { get; set; }
    }
}
