//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienie_szczegol_pojazd
    {
        public int ID_zamowienie_szczegol_pojazd { get; set; }
        public int Nr_zamówienia { get; set; }
        public string Nr_VIN { get; set; }
        public int Ilosc { get; set; }
        public int ID_gwarancja { get; set; }
        public string Opis_gwarancja { get; set; }
        public int ID_pojazd { get; set; }
        public int Koszt { get; set; }
    }
}
