//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praca_mgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.Reklamacja_pojazd = new HashSet<Reklamacja_pojazd>();
            this.Reklamacja_produkt = new HashSet<Reklamacja_produkt>();
            this.Zamowienie_szczegol = new HashSet<Zamowienie_szczegol>();
            this.Zamowienie_szczegol_pojazd = new HashSet<Zamowienie_szczegol_pojazd>();
        }
    
        public int ID_zamowienie { get; set; }
        public Nullable<int> ID_klient { get; set; }
        public int ID_pracownik { get; set; }
        public System.DateTime Data_zamowienie { get; set; }
        public int ID_typ_zamowienie { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja_pojazd> Reklamacja_pojazd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja_produkt> Reklamacja_produkt { get; set; }
        public virtual Typ_zamowienie Typ_zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol_pojazd> Zamowienie_szczegol_pojazd { get; set; }
    }
}
